export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const TABLE_SUCCESS="TABLE_SUCCESS";
export const TABLE_FAIL="TABLE_FAIL";

export const OPTION_SUCCESS="OPTION_SUCCESS";
export const OPTION_FAIL="OPTION_FAIL";

export const EDUCATOR_TABLE_SUCCESS="EDUCATOR_TABLE_SUCCESS";
export const EDUCATOR_TABLE_FAIL="EDUCATOR_TABLE_FAIL";

export const STUDENT_TABLE_SUCCESS="STUDENT_TABLE_SUCCESS";
export const STUDENT_TABLE_FAIL="STUDENT_TABLE_FAIL";

export const SPINEER_SUCCESS="SPINEER_SUCCESS";
export const ERROR_SUCCESS="ERROR_SUCCESS";

export const SCHEDULE_TYPE_SUCCESS="SCHEDULE_TYPE_SUCCESS";
export const SCHEDULE_TYPE_FAIL="SCHEDULE_TYPE_FAIL";
export const SCHEDULE_SUCCESS="SCHEDULE_SUCCESS";
export const SCHEDULE_FAIL="SCHEDULE_FAIL";


export const Q_SUCCESS="Q_SUCCESS";
export const QUESTION_APPEND_SUCCESS="QUESTION_APPEND_SUCCESS";
export const Q_FAIL="Q_FAIL";
export const ADD_FILTER_SUCCESS = "ADD_FILTER_SUCCESS";
export const TOGGLE_APPROVED = "TOGGLE_APPROVED";
export const CHANGE_PAGE_NUMBER = "CHANGE_PAGE_NUMBER";
export const CHANGE_INDEX = "CHANGE_INDEX";

export const REWARD_SUCCESS="REWARD_SUCCESS";
export const REWARD_FAIL="REWARD_FAIL"

export const BOARD_SUCCESS = "BOARD_SUCCESS";
export const BOARD_FAIL = "BOARD_FAIL";
export const MEDIUM_SUCCESS = "MEDIUM_SUCCESS";
export const MEDIUM_FAIL = "MEDIUM_FAIL";
export const CLASS_SUCCESS = "CLASS_SUCCESS";
export const CLASS_FAIL = "CLASS_FAIL";
export const SUBJECT_SUCCESS = "SUBJECT_SUCCESS";
export const SUBJECT_FAIL = "SUBJECT_FAIL";
export const LEVEL_SUCCESS = "LEVEL_SUCCESS";
export const LEVEL_FAIL = "LEVEL_FAIL";
export const STATE_SUCCESS = "STATE_SUCCESS";
export const STATE_FAIL = "STATE_FAIL";

