export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const TABLE_SUCCESS="TABLE_SUCCESS";
export const TABLE_FAIL="TABLE_FAIL";



export const STUDENT_TABLE_SUCCESS="STUDENT_TABLE_SUCCESS";
export const STUDENT_TABLE_FAIL="STUDENT_TABLE_FAIL";
export const STUDENT_SEARCH_SUCCESS="STUDENT_SEARCH_SUCCESS";

export const ALL_DIET_SUCCESS="ALL_DIET_SUCCESS"
export const CURRENT_DIET_SUCCESS="CURRENT_DIET_SUCCESS";
export const SWAP_FOOD_SUCCESS="SWAP_FOOD_SUCCESS";

export const SPINEER_SUCCESS="SPINEER_SUCCESS";
export const ERROR_SUCCESS="ERROR_SUCCESS";




